services:
  bingfox:
    image: bingfox
    container_name: bingfox
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PORT=3099 # Of 3099 als de server dit ondersteunt
    volumes:
      - ./bingfox/data/:/app/data/
    restart: unless-stopped